# Generated by Django 4.2.11 on 2024-05-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendor_insights", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="acknowledgment_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the vendor acknowledged the PO.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="quality_rating",
            field=models.FloatField(
                blank=True,
                help_text="Rating given to the vendor for this PO",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="average_response_time",
            field=models.FloatField(
                default=0.0,
                help_text="Average time taken to acknowledge purchase orders.",
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="fulfillment_rate",
            field=models.FloatField(
                default=0.0,
                help_text="Percentage of purchase orders fulfilled successfull",
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="on_time_delivery_rate",
            field=models.FloatField(
                default=0.0, help_text="Tracks the percentage of on-time deliveries."
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="quality_rating_avg",
            field=models.FloatField(
                default=0.0,
                help_text="Average rating of quality based on purchase orders",
            ),
        ),
    ]
